import Footer from "@/components/footer";
import Header from "@/components/header/header";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  // variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  // variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Arifur Rahman - React Front-end Web Developer | Tech Enthusiast",
  description: "Generated by @developerarif",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.className} ${geistMono.className} antialiased`}
      >
        <section className="mx-52 my-10">
          <Header />
          {children}
          <Footer />
        </section>
      </body>
    </html>
  );
}
